### ISSUE TITLE
Transition between resized border links doesn't work after rebooting Mac without manual open or display change

### ISSUE THREAD

**Issue by BATIA007** [bitgapp/Cursr#118]
Version: 1.7.2
MacBook Air M4
MacOS Tahoe 26.1

When I reboot (or shut down) my Mac, resizing border links doesn't work, but Cursr is running in the background (It eats ~35% of a CPU core when the mouse is moving).

It can be fixed with 2 ways:
1) Plug in monitors after logging into the system.
2) Manually open Cursr after logging into the system. Just open and close it, and it will work properly.

**Comment by ragauskl** [comment]
Do you mean that moving mouse 'between resized borders' does not work? Because they can only be resized when Cursr is open which you mention in solution no2 or in solution 2 you mean that first you have to minimize/close the app window and then reopen it?

As you're on v1.7.2 which is one year old at this point I'd recommend first enabling 'Early Access' and updating to latest version or wait a bit until it's made stable (it technically is, I'm just doing last testing steps at the moment)

**Comment by BATIA007** [comment]
<img width="1574" height="586" alt="Image" src="https://github.com/user-attachments/assets/81cb3135-2278-4e57-91c5-57d287f2eb73" />

I mean I have this structure in Cursr, and when I reboot or shut down Mac, it won't work after I log in. It works only when I open Cursr manually after rebooting, then I can just close/minimize it. So "Launch on Startup" doesn't work for this scenario, because it needs to be opened manually.

Updating to the latest version doesn't help, because Constrain Mode doesn't work in this version, so I downgraded back.

**Comment by ragauskl** [comment]
Constraint mode should be working, I'll look into it and see if there's a bug

You said Cursr is running in the background before you open manually so 'Launch on Startup' is working as all it does is open the app, if it the transition between displays don't work then it's a different cause/issue.

I see that your setup is not saved (says unsaved in top right corner with highlighted save button), try saving the setup and see if that helps. Cursr has 2 slots for unsaved setups to ensure changes are not lost if user by accident does something that triggers OS display change, without getting into too much detail, this could be the cause. Saved setups take priority over unsaved ones so that may resolve your case. If not, then next step would still be updating but I recommend waiting for stable 1.7.3 as I'll look into the constraint border issue before it's released

**Comment by BATIA007** [comment]
Saving setup doesn't help.
Will be waiting for v1.7.3. Anyway it's not a big deal to open manually Cursr on startup.

**Comment by BATIA007** [comment]
Updated to v1.7.3 and Constraint mode is working now. 

But transition still doesn't work on startup; it needs to be opened manually. Maybe Cursr starts working too soon and something is missing at this moment, but monitors start working immediately after the login screen, and other apps are still loading at this moment, so Cursr should be loading too. I've disabled all other apps on startup, and it still doesn't work, so applications don't block Cursr behavior. Also, when I reconnect 1 of the external monitors, it starts working properly; I think there's a listener on the connecting event that calls a function to set up monitors, the same function I think triggers when I open Cursr manually. But for some reason, this function doesn't work properly on startup.

**Comment by ragauskl** [comment]
May I ask you to go to Settings > General and for 'Debug' select 'Mouse/Transitions','Other' and 'Setups'. Then restart your device, replicate the issue by trying to move between the displays, open Cursr and move the mouse between displays again.

Optionally, but may be useful if you can again restart the device but this time use the workaround of reconnecting the monitors.

Then below the 'Debug' you'll find 'Logs', click on 'Compress Logs' and forward these to me by email contact@cursr.app .
